#!/bin/bash
set -ex
user="$(stat -f '%Su' /dev/console)"
HOME="/Users/${user}"
uagents="$HOME/Library/LaunchAgents"
plist="net.cooperi.pivy-agent.plist"

if /usr/bin/su "$user" -c "/bin/launchctl list \"net.cooperi.pivy-agent\"" > /dev/null; then
    /usr/bin/su "$user" -c "/bin/launchctl unload \"$uagents/$plist\""
fi
